import { applyTheme, md, preprocessMarkdown } from './markdown';
import { THEMES } from './themes';
import { prepareHtmlForExport } from './htmlExport';

export interface TemplateSection {
    heading?: string;
    body?: string | string[];
    bullets?: string[];
    quote?: string;
    image?: {
        url: string;
        alt?: string;
    };
}

export interface HtmlTemplateParameters {
    title?: string;
    subtitle?: string;
    author?: string;
    date?: string;
    summary?: string;
    markdown?: string;
    sections?: TemplateSection[];
    cta?: {
        label: string;
        url: string;
    };
    theme?: string;
}

export interface RenderMarkdownToHtmlOptions {
    title?: string;
    markdown?: string;
    theme?: string;
    parameters?: HtmlTemplateParameters;
}

function escapeHtml(value: string): string {
    return value
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#39;');
}

function normalizeLines(value: string | string[]): string[] {
    return Array.isArray(value) ? value : [value];
}

export function buildMarkdownFromTemplate(parameters: HtmlTemplateParameters): string {
    const parts: string[] = [];

    if (parameters.title) parts.push(`# ${parameters.title}`);
    if (parameters.subtitle) parts.push(`> ${parameters.subtitle}`);
    if (parameters.author || parameters.date) {
        parts.push([parameters.author, parameters.date].filter(Boolean).join(' · '));
    }
    if (parameters.summary) parts.push(`## 摘要\n\n${parameters.summary}`);
    if (parameters.markdown) parts.push(parameters.markdown);

    parameters.sections?.forEach((section) => {
        const sectionParts: string[] = [];
        if (section.heading) sectionParts.push(`## ${section.heading}`);
        if (section.body) sectionParts.push(normalizeLines(section.body).join('\n\n'));
        if (section.bullets?.length) {
            sectionParts.push(section.bullets.map((bullet) => `- ${bullet}`).join('\n'));
        }
        if (section.quote) sectionParts.push(`> ${section.quote}`);
        if (section.image?.url) {
            sectionParts.push(`![${section.image.alt || ''}](${section.image.url})`);
        }
        if (sectionParts.length > 0) parts.push(sectionParts.join('\n\n'));
    });

    if (parameters.cta?.label && parameters.cta.url) {
        parts.push(`[${parameters.cta.label}](${parameters.cta.url})`);
    }

    return parts.join('\n\n').trim();
}

export async function renderMarkdownToHtml(options: RenderMarkdownToHtmlOptions | HtmlTemplateParameters): Promise<string> {
    const parameters = 'parameters' in options && options.parameters ? options.parameters : options;
    const themeId = parameters.theme || options.theme || THEMES[0].id;
    const theme = THEMES.find((candidate) => candidate.id === themeId) || THEMES[0];
    const markdown = options.markdown || buildMarkdownFromTemplate(parameters);
    const title = parameters.title || options.title || 'Raphael Publish HTML';
    const rawHtml = md.render(preprocessMarkdown(markdown));
    const styledHtml = applyTheme(rawHtml, theme.id);
    const exportHtml = await prepareHtmlForExport(styledHtml);

    return [
        '<!doctype html>',
        '<html lang="zh-CN">',
        '<head>',
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<meta name="generator" content="Raphael Publish">',
        `<meta name="raphael-theme" content="${escapeHtml(theme.id)}">`,
        `<title>${escapeHtml(title)}</title>`,
        '</head>',
        `<body data-raphael-theme="${escapeHtml(theme.id)}" data-raphael-theme-name="${escapeHtml(theme.name)}">`,
        `<!-- Generated by Raphael Publish with theme: ${escapeHtml(theme.name)} (${escapeHtml(theme.id)}) -->`,
        exportHtml,
        '</body>',
        '</html>',
    ].join('\n');
}
